<?php

namespace App\Consumer;

class PostConsumer extends BaseConsumer
{
    protected $url = 'posts';

    public function all()
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }

    public function only(int $id)
    {
        return parent::get($id); // TODO: Change the autogenerated stub
    }

    public function comments($postId)
    {
        return parent::get("$postId/comments");
    }
}
